### ISSUE TITLE
Invalid 'expires' attribute? 

### ISSUE THREAD

**Issue by joelkuiper** [dakrone/clj-http#325] opened 2016-06-23 10:57 UTC
ResponseProcessCookies:129 - Invalid cookie header: "Set-Cookie: ncbi_sid=73BE402676BBFF01_0927SID; domain=.nih.gov; path=/; expires=Fri, 23 Jun 2017 10:54:40 GMT". Invalid 'expires' attribute: Fri, 23 Jun 2017 10:54:40 GMT

When executing a GET I get this message, is it simply a server misconfiguration or something else going on?

**Comment by dakrone** [comment] 2016-06-27 22:59
Do you have the full stack trace for this error?

**Comment by joelkuiper** [comment] 2016-06-29 13:34
Just shows up as a warning here, no stack trace 

`2016-06-29 15:33:31 WARN  ResponseProcessCookies:129 - Invalid cookie header: "Set-Cookie: ncbi_sid=9DFD5C99773CE2B1_0917SID; domain=.nih.gov; path=/; expires=Thu, 29 Jun 2017 13:33:31 GMT". Invalid 'expires' attribute: Thu, 29 Jun 2017 13:33:31 GMT`

**Comment by dakrone** [comment] 2016-07-03 17:00
Okay, since this is marked as fixed in 4.5, it *should* be fixed in the latest clj-http which uses a 4.5 version of the client.

What version of clj-http are you using? Does upgrading fix this?

**Comment by yang-wei** [comment] 2016-07-17 01:39
Same problem here 
using 3.1.0 of clj-http

**Comment by dakrone** [comment] 2016-10-16 22:53
Has anyone had a chance to try this with clj-http 3.3.0?

**Comment by drewr** [comment] 2016-11-07 03:21
Confirm it still fails with 3.3.0:
```
Nov 06, 2016 9:19:57 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: fr=0ZcB4dEGC2q4MqVrd..BYH_Ld.Am.AAA.0.0.BYH_Ld.AWXCoUKJ; Expires=Sun, 5 Feb 2017 02:49:38 GMT; Path=/; Version=0". Invalid 'expires' attribute: Sun, 5 Feb 2017 02:49:38 GMT
```

**Comment by eivindw** [comment] 2017-04-26 13:03
Also still failing with the 3.5.0 version:

```
Apr 26, 2017 3:00:42 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: user_id="2|1:0|10:1493211642|7:user_id|44:ZDQ0NmIxYmRjOTE0NDgxZjljNzFhZTMxNzBiYjkyZmU=|87307f9664bd33350c039cd1d5ecc3bb8782c68ec890ba4fde5150b57168cc12"; expires=Fri, 26 May 2017 13:00:42 GMT; Path=/". Invalid 'expires' attribute: Fri, 26 May 2017 13:00:42 GMT
```

**Comment by eivindw** [comment] 2017-04-28 20:04
Overriding the cookie-policy on the request to "standard" fixed the problem for me - in case anyone else has the same problem:
```clojure
  (client/post login-url
    {:body (ch/generate-string {"email" "..." "password" "..."})
     :content-type :json
     :cookie-policy :standard
     :cookie-store cs
     :headers {"x-xsrftoken" (get-token)}})
```
As suggested in [this thread on stackoverflow](http://stackoverflow.com/questions/36473478/fixing-httpclient-warning-invalid-expires-attribute-using-fluent-api).

**Comment by borkdude** [comment] 2017-05-12 15:30
Confirmed, `:cookie-policy :standard` solves this.

**Comment by douglasoviche** [comment] 2017-11-15 20:14
You guys saved me a lot of wasted time. I've been all afternoon after this answer.
Thanks very much

**Comment by dakrone** [comment] 2018-02-27 04:01
I think I'm going to close this since there's a workaround for it (setting `:cookie-policy :standard`). Let me know if anyone disagrees and I'll re-open.

**Closed by dakrone** 2018-02-27 04:01 UTC

**Comment by eigenhombre** [comment] 2019-05-22 18:55
@dakrone Might be adding a note in the README around the part where it explains how to set up the cookie store?  Anyways, thanks for the workaround.

**Comment by conan** [comment] 2022-12-19 14:38
I'm experiencing this issue, maybe needs another HttpClient bump? Looks like 5.1.3 is compliant (current version is 4.5.13)

https://stackoverflow.com/questions/36473478/fixing-httpclient-warning-invalid-expires-attribute-using-fluent-api/73764182#73764182

EDIT: we can use `:cookie-policy :none` if we aren't using cookies, which solved the issue for me.  See [comment in another issue about this](https://github.com/dakrone/clj-http/issues/579#issuecomment-749268689)

**Comment by dakrone** [comment] 2022-12-19 16:14
I'd love to bump to 5.x, however, it's a very large change due to breaking changes between 4.x and 5.x, and I haven't had the time to be able to devote to it.
