### ISSUE TITLE
using :form-params errors out "ArityException Wrong number of args (2) passed to: util/url-encode"

### ISSUE THREAD

**Issue by ccod** [dakrone/clj-http#250] opened 2015-01-22 15:58 UTC
using version "1.0.1" these calls should reproduce the problem:
(client/get "http://www.google.com" {:query-params {:foo "bar"}})
(client/put "http://www.google.com" {:form-params {:foo "bar"}})

moving down to version "0.9.2" brought me back to a working state.

**Comment by joegallo** [comment] 2015-01-22 16:08
Hmmm... both of those calls work fine for me, I'm not seeing that exception. Is it possible you have out of date compiled class files hanging around? If so, perhaps `lein clean` will resolve your issue.

**Comment by ccod** [comment] 2015-01-22 18:18
unfortunately lein clean did not help.

**Comment by dakrone** [comment] 2015-01-23 15:01
@ccod can you paste the output of `lein deps :tree` here, perhaps there is another dependency that is interfering with the newer clj-http

**Comment by looselytyped** [comment] 2015-02-02 17:34
@ccod - I got the same error and came here to report an issue. Considering @joegallo could not reproduce it got me thinking - maybe it's my `profiles.clj` - Turns out that I had `:dependencies [[leiningen #=(leiningen.core.main/leiningen-version)]]` and `(inject/in [vinyasa.lein :exclude [*project*]]` in my `profiles.clj` - Commenting those out seem to fix the issue. 

Unfortunately I am not proficient enough to debug how those interact with each other, but perhaps this will help @joegallo (and you) get past this issue.

**Comment by va1en0k** [comment] 2015-02-11 15:49
I have the same problem with 1.0.1, while using it with `chestnut 0.6.0`. No other dependencies inroduced, other than the chestnuts' plentyful.

The `lein deps :tree` gives lots of warnings stuff, so I put it in a gist:https://gist.github.com/va1en0k/a858b1ef8ca34752f7d2

Would be glad to hear any suggestions.

**Comment by drakezhard** [comment] 2015-02-13 17:38
I was having the same problem with 1.0.1 and chestnut 0.6.0, I upgraded leiningen from 2.5.0 to 2.5.1 and lo and behold it went through.

**Comment by dakrone** [comment] 2015-07-25 20:36
Closing this, feel free to re-open if you see it again.

**Closed by dakrone** 2015-07-25 20:36 UTC
